### ISSUE TITLE
Can you provide the workflow files?

### ISSUE THREAD

**Issue by quqiufeng** [jags111/ComfyUI_Jags_VectorMagic#4]
Can you provide the workflow documentation?

**Comment by jags111** [comment]
sure will add it in WIKI and update same

**Comment by quqiufeng** [comment]
![微信截图_20240605204248](https://github.com/jags111/ComfyUI_Jags_VectorMagic/assets/839168/5913ae62-6a56-4fa6-afa5-8f65af223fb2)

my first  try  , it's not so good.  wait for your workflow file

**Comment by quqiufeng** [comment]
whereis the file Graphic_XL.safetensors?

**Comment by schananas** [comment]
@quqiufeng did you find Graphic_XL.safetensors and where?
